version: '3.1'

services:

  trader:
    build:
      context: .
    volumes:
      - .:/trader
    env_file:
      - .env
    networks:
      - llama_api

volumes:
  app: {}

networks:
  llama_api:
    external: true